version: '3.0'

services:

  db:
    image: postgres:13.1-alpine
    container_name: liki_db
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "7777:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: liki
    networks:
      - backend

  app:
    image: na1al/liki_app
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: liki_app
    depends_on:
      - db
    volumes:
      - ./uploads:/var/uploads
    ports:
      - "8081:8080"
    networks:
      - backend

  web:
    image: na1al/liki_web
    build:
      context: ./web
      dockerfile: Dockerfile.release
    container_name: liki_web
    depends_on:
      - app
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./uploads:/var/uploads
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
