# build stage
FROM node:lts-alpine as build-stage

WORKDIR /www

COPY www .

RUN npm install

RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /www/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
